Repository DkreativeCoders/dmessanger-service, pull requests merged in 2020-05, with the labels that each got.

#4 basic swagger setup for api documentation
  README.md
  pkg/server/main.go
  swagger.json
Labels: documentation

#5 Ab dev
  cmd/server/main.go
  go.mod
  go.sum
  pkg/domain/courier.go
  pkg/domain/customer.go
  pkg/domain/irepository/iuserrepository.go
  pkg/domain/iservice/iuserservice.go
  pkg/domain/user.go
  pkg/migrations/gmorm/mysql-db-connections.go
  pkg/new_routes.go
  pkg/user/controller/chttp/user_handler.go
  pkg/user/repository/orm/orm_user.go
  pkg/user/service/userservice.go
  pkg/utils/util.go
Labels: enhancement

#11 Added test for Utils and User package
  pkg/domain/user_test.go
  pkg/utils/util_test.go
Labels: enhancement

#12 refactored docs and bindings
  cmd/server/main.go
  doc/doc.go
  pkg/doc.go
  pkg/domain/binding/bindings.go
  pkg/domain/iservice/iuserservice.go
  pkg/user/controller/chttp/user_handler.go
  pkg/user/doc/paramters.go
  pkg/user/doc/responses.go
  pkg/user/dto/request.go
  pkg/user/dto/response.go
  pkg/user/service/userservice.go
  pkg/utils/util.go
  swagger.json
Labels: documentation, refactor

#13 Added test for User service
  go.mod
  go.sum
  pkg/mocks/UserRepository.go
  pkg/user/service/userservice_test.go
Labels: test

#15 Customer registration refactoring
  pkg/customer/controller/chttp/customer_handler.go
  pkg/customer/doc/responses.go
  pkg/customer/dto/response.go
  pkg/customer/repository/orm/orm_customer.go
  pkg/customer/service/customerservice.go
  pkg/domain/customer.go
  pkg/new_routes.go
  swagger.json
Labels: refactor

#16 Improved swagger documentation
  pkg/customer/doc/paramters.go
  pkg/customer/doc/responses.go
  pkg/customer/dto/request.go
  pkg/customer/dto/response.go
  pkg/domain/courier.go
  pkg/domain/customer.go
  pkg/domain/defaultresponse/defaultresponsedata.go
  pkg/domain/defaultresponse/docdefaultresponsedata.go
  pkg/domain/user.go
  pkg/user/doc/paramters.go
  pkg/user/doc/responses.go
  pkg/user/dto/request.go
  pkg/user/dto/response.go
  swagger.json
Labels: refactor

#21 User Registration
  example.env
  go.mod
  go.sum
  pkg/config/mail/Imail.go
  pkg/config/mail/mailgunImpl.go
  pkg/customer/controller/chttp/customer_handler.go
  pkg/customer/doc/paramters.go
  pkg/customer/doc/responses.go
  pkg/customer/dto/request.go
  pkg/customer/dto/response.go
  pkg/customer/repository/orm/orm_customer.go
  pkg/customer/service/customerservice.go
  pkg/doc.go
  pkg/domain/customer.go
  pkg/domain/defaultresponse/defaultresponsedata.go
  pkg/domain/defaultresponse/docdefaultresponsedata.go
  pkg/domain/irepository/itokenrepository.go
  pkg/domain/iservice/icustomerservice.go
  pkg/domain/token.go
  pkg/domain/user.go
  pkg/domain/user_test.go
  pkg/migrations/IDialect.go
  pkg/migrations/gmorm/mysql-db-connections.go
  pkg/mocks/UserRepository.go
  pkg/new_routes.go
  pkg/token/repository/orm/orm_token.go
  pkg/user/controller/chttp/user_handler.go
  pkg/user/doc/paramters.go
  pkg/user/doc/responses.go
  pkg/user/dto/request.go
  pkg/user/dto/response.go
  pkg/user/repository/orm/orm_user.go
  pkg/user/service/userservice.go
  pkg/user/service/userservice_test.go
  pkg/utils/util.go
  pkg/utils/util_test.go
Labels: enhancement

#22 Placed app in good run state
  example.env
  pkg/customer/service/customerservice.go
  pkg/domain/user.go
  pkg/new_routes.go
  pkg/user/controller/chttp/user_handler.go
  pkg/user/service/userservice.go
  pkg/user/service/userservice_test.go
Labels: enhancement
